version: "3.3"
services:
  open-webui:
    ports:
      - 3000:8080
    environment:
      - OLLAMA_BASE_URL=http://10.0.1.3:11434
    volumes:
      - /media/Colo/Server/Persistent-Storage/open-webui:/app/backend/data
    container_name: open-webui
    restart: always
    image: ghcr.io/open-webui/open-webui:main
    networks:
      - caddy
    labels:
      caddy: openai.domain.dk
      caddy.reverse_proxy: "{{upstreams 8080}}"
networks:
  caddy:
