services:

 portainer_agent:
  
    container_name: "portainer_agent"
    entrypoint:
      - "./agent"
    environment:
      - "PATH=/app:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    hostname: "6fe4aec290f8"
    image: "portainer/agent:2.19.3"
    ipc: "private"
    labels:
      io.portainer.agent: "true"
    logging:
      driver: "json-file"
      options: {}
    mac_address: "02:42:ac:11:00:04"
    network_mode: "bridge"
    ports:
      - "9001:9001/tcp"
    restart: "always"
    volumes:
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: "/app"
