name: ntp-chrony
services:
  chrony:
    image: publicarray/chrony:latest
    container_name: Chrony
    restart: unless-stopped
    ports:
    - 123:123/udp
    volumes:
    - /media/Colo/Server/Persistent-Storage/chrony/chrony.conf:/etc/chrony.conf
    cap_add:
    - SYS_TIME
    network_mode: bridge
#
#remember to create /etc/chrony.conf and add this to the bottom of the file
#
#
#
#server 0.dk.pool.ntp.org iburst
#server 1.dk.pool.ntp.org iburst
#server 2.pool.ntp.org iburst
#server 3.pool.ntp.org iburst
#
#keyfile /etc/chrony/chrony.keys
#driftfile /var/lib/chrony/chrony.drift
#logdir /var/log/chrony
#maxupdateskew 100.0
#rtcsync
#makestep 1 3
#allow 10.0.1.0/24
#
#
#
#
#
#
#