services:

  sonarr:

    container_name: "sonarr"

    #dns:
    #  - "10.20.30.55"

    entrypoint:
      - "/init"

    environment:
      - "PGID=1000"
      - "TZ=Etc/UTC"
      - "PUID=1000"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/root"
      - "LANGUAGE=en_US.UTF-8"
      - "LANG=en_US.UTF-8"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "XDG_CONFIG_HOME=/config/xdg"
      - "SONARR_BRANCH=main"

    image: "lscr.io/linuxserver/sonarr:latest"

    #labels:
    #  caddy: sonarr.domain.dk
    #  caddy.@denied.not: "remote_ip 100.64.0.0/10 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
    #  caddy.abort: "@denied"
    #  caddy.reverse_proxy: "{{upstreams 8989}}"
    logging:
      driver: "json-file"
      options: {}

    network_mode: "container:gluetun"

    #ports:
    #  - "8989:8989/tcp"

    restart: "unless-stopped"

    volumes:
      - "/media/Colo:/media"
      - "/media/Colo/Server/Persistent-Storage/sonarr:/config"

    working_dir: "/"

    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
networks:
  gluetun_network:
   external: true