version: "3.7"

services:
  grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - "81:5000"  # host:docker
    environment:
      GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampswebredis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampswebredis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampswebredis:6379/1
    labels:
      caddy: gramps.domain.dk
      caddy.reverse_proxy: 10.0.1.151:81
      kompose.service.expose: "my.url"
    depends_on:
      - grampswebredis
    volumes:
      - /media/Colo/Server/Persistent-Storage/gramps/app/users:/app/users  # persist user database
      - /media/Colo/Server/Persistent-Storage/gramps/app/indexdir:/app/indexdir  # persist search index
      - /media/Colo/Server/Persistent-Storage/gramps/app/thumbnail_cache:/app/thumbnail_cache  # persist - thumbnails
      - /media/Colo/Server/Persistent-Storage/gramps/app/cache:/app/cache  # persist export and report caches
      - /media/Colo/Server/Persistent-Storage/gramps/app/secret:/app/secret  # persist flask secret
      - /media/Colo/Server/Persistent-Storage/gramps/grampsdb:/root/.gramps/grampsdb  # persist Gramps database
      - /media/Colo/Server/Persistent-Storage/gramps/app/media:/app/media  # persist media files
      - /media/Colo/Server/Persistent-Storage/gramps/tmp:/tmp


  grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    container_name: grampsweb_celery
    depends_on:
      - grampswebredis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO

  grampswebredis:
    image: redis:alpine
    container_name: grampswebredis
    restart: always
    volumes:
      - /media/Colo/Server/Persistent-Storage/gramps/redis:/data
    ports:
      - "6379"
    networks:
      - gramps-network


#volumes:
 # gramps_users:
 # gramps_index:
 # gramps_thumb_cache:
 # gramps_cache:
 # gramps_db:
 # gramps_media:
 # gramps_tmp:


networks:
  gramps-network:
   external: true