services:

 prowlarr:

    container_name: "prowlarr"

    #dns:
    #  - "10.20.30.55"

    entrypoint:
      - "/init"

    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Etc/UTC"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$"
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "XDG_CONFIG_HOME=/config/xdg"

    image: "lscr.io/linuxserver/prowlarr:latest"
    
    logging:
      driver: "json-file"
      options: {}

    network_mode: "container:gluetun"

    #ports:
    #  - "9696:9696/tcp"
    #labels:
    #  caddy: prowlarr.domain.dk
    #  caddy.@denied.not: "remote_ip 100.64.0.0/10 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
    #  caddy.abort: "@denied"
    #  caddy.reverse_proxy: "{{upstreams 9696}}"
    restart: "unless-stopped"

    volumes:
      - "/media/Colo:/media"
      - "/media/Colo/Server/Persistent-Storage/prowlarr:/config"

    working_dir: "/"

    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      
    healthcheck: 
     test: curl --fail http://localhost:9696 || exit 1 
     interval: 10s 
     retries: 5 
     start_period: 5s 
     timeout: 10s
networks:
  gluetun_network:

    external: true