services:

 jellyfin:

    container_name: "jellyfin"

    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"

    entrypoint:
      - "/init"

    environment:
      - "JELLYFIN_LOG_DIR=/var/log/jellyfin"
      - "PUID=114"
      - "PGID=121"
      - "TZ=Etc/UTC"
      - "JELLYFIN_CACHE_DIR=/var/cache/jellyfin"
      - "JELLYFIN_CONFIG_DIR=/etc/jellyfin"
      - "JELLYFIN_DATA_DIR=/var/lib/jellyfin"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/root"
      - "LANGUAGE=en_US.UTF-8"
      - "LANG=en_US.UTF-8"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility"
    healthcheck: 
     test: curl --fail http://localhost:8096 || exit 1 
     interval: 10s 
     retries: 5 
     start_period: 5s 
     timeout: 10s

    image: "lscr.io/linuxserver/jellyfin:latest"

    networks:
      - caddy
    labels:
      caddy: jellyfin.domain.dk
      caddy.reverse_proxy: "{{upstreams 8096}}"

      caddy.redir: /jellyfin /jellyfin/
    logging:
      driver: "json-file"
      options: {}

    ports:
      #- "1901:1900/udp"
      - "7359:7359/udp"
      - "8096:8096/tcp"
      - "8920:8920/tcp"

    restart: "unless-stopped"

    volumes:
      - "/media/Colo/Server/Persistent-Storage/jellyfin/etc/jellyfin:/etc/jellyfin"
      - "/media/Colo:/media/Colo"
      - "/var/cache/jellyfin:/var/cache/jellyfin"
      - "/media/Colo/Server/Persistent-Storage/jellyfin/var/lib/jellyfin:/var/lib/jellyfin"
      - "/media/Colo/Server/Persistent-Storage/jellyfin/var/log/jellyfin:/var/log/jellyfin"
      - "/media/Colo/Server/Persistent-Storage/jellyfin/config:/config"

    working_dir: "/"
networks:
   caddy:
    external: true
